// Every string the user sees lives here (English first). To translate: add another table with the same keys and
// pick it in `currentLanguage`. {name} placeholders are filled by t().

export const en = {
  "app.name": "gigradar",
  "app.loading": "Checking your setup…",

  "nav.back": "Back",
  "nav.next": "Next",
  "nav.stepOf": "Step {n} of {total}",
  "nav.steps": "Setup steps",

  "step.welcome": "Welcome",
  "step.profile": "Profile",
  "step.preferences": "Preferences",
  "step.searches": "Searches",
  "step.notifications": "Notifications",
  "step.upwork": "Upwork check",
  "step.model": "Scoring model",
  "step.finish": "Finish",

  "welcome.title": "Welcome to gigradar",
  "welcome.body1": "gigradar watches Upwork for new jobs that match what you do, so you don't have to keep refreshing the page.",
  "welcome.body2": "It scores every new job against your profile and tells you about the good ones with a notification on this PC and, if you like, in Telegram.",
  "welcome.body3": "Everything stays on your computer. Setup takes about five minutes, and you can change it later.",
  "welcome.start": "Get started",

  "profile.title": "Tell us what you do",
  "profile.lead": "Paste a short description of your skills and the work you want. It is only used on this PC to rate jobs.",
  "profile.label": "Your profile",
  "profile.placeholder": "Example:\n\n## Web development\nI build web apps with TypeScript, React and Node.js …\n\n## Data work\nI write Python scripts that clean and analyse data …",
  "profile.helpTitle": "No profile yet?",
  "profile.helpBody": "Ask Claude to write one with you. Copy the request below, paste it into a chat with Claude, answer its questions, then paste the result here.",
  "profile.copy": "Copy prompt for Claude",
  "profile.copied": "Copied. Paste it into a chat with Claude.",
  "profile.copyFailed": "Could not copy. Select the text below and copy it yourself.",
  "profile.promptLabel": "The request for Claude",
  "profile.wrapped": "We added a heading to your text so it can be used as one skill area.",
  "profile.tooShort": "Please write at least a few words about what you do.",

  "profile.prompt":
    "I am a freelancer. I want a short profile that an app will use to match Upwork job posts against my skills.\n\n" +
    "Ask me questions one at a time to learn what I do (my main skills, the kinds of projects I enjoy, tools I use, and what I do NOT want to work on). " +
    "After a few questions, write my profile.\n\n" +
    "Format rules for the final answer:\n" +
    "- Plain Markdown, in English.\n" +
    "- 2 to 6 skill areas. Each one starts with a line like \"## Web development\" (two # characters, a space, a short name).\n" +
    "- Under each heading write 2 to 4 sentences in the first person describing the work, the tools and the typical projects.\n" +
    "- No other headings, no lists of buzzwords, no contact details.\n" +
    "- Reply with only the finished profile in one code block so I can copy it.",

  "prefs.title": "What matters to you",
  "prefs.lead": "All of this is optional. It helps gigradar rank jobs, and you can leave a field empty.",
  "prefs.skills": "Your main skills",
  "prefs.skillsHint": "Type a skill and press Enter. Jobs that list these skills score higher.",
  "prefs.skillsPlaceholder": "e.g. Python",
  "prefs.addSkill": "Add skill",
  "prefs.removeSkill": "Remove {name}",
  "prefs.constraints": "Anything a job must fit (optional)",
  "prefs.constraintsHint": "Where and when you can work. Jobs that clearly don't fit are ranked low.",
  "prefs.constraintsPlaceholder": "e.g. Remote only; based in <country> (<time zone>); no on-site work",
  "prefs.minHourly": "Lowest hourly rate (USD, optional)",
  "prefs.minFixed": "Lowest fixed price (USD, optional)",
  "prefs.number": "Please enter a number, or leave the field empty.",

  "search.title": "What should we look for?",
  "search.lead": "Add up to {max} searches. gigradar runs each one every half hour and tells you about new jobs.",
  "search.n": "Search {n}",
  "search.keywords": "Keywords",
  "search.keywordsPlaceholder": "e.g. python automation",
  "search.type": "Pay type",
  "search.hourly": "Hourly",
  "search.fixed": "Fixed price",
  "search.both": "Both",
  "search.note": "Every search is one request to Upwork per check, so more searches mean more requests. A few focused searches work best.",
  "search.add": "Add another search",
  "search.remove": "Remove search {n}",
  "search.needOne": "Enter keywords for at least one search.",

  "notify.title": "How should we tell you?",
  "notify.lead": "Pick where new jobs are announced. You can use both.",
  "notify.toast": "Notifications on this PC",
  "notify.toastHint": "A small message appears in the corner of your screen.",
  "notify.toastTest": "Send a test notification",
  "notify.toastTestOk": "Sent. Did a notification appear in the corner of your screen?",
  "notify.toastTestFailed": "The test notification did not work: {message}",
  "notify.telegram": "Telegram messages",
  "notify.telegramHint": "Get jobs on your phone too. You create your own private bot; it takes about two minutes.",
  "notify.guideTitle": "Create your Telegram bot",
  "notify.guide1": "In Telegram, open a chat with @BotFather and send /newbot.",
  "notify.guide2": "Choose a name and a username for your bot. BotFather then replies with a long token.",
  "notify.guide3": "Copy that token and paste it below.",
  "notify.openBotFather": "Open BotFather",
  "notify.tokenLabel": "Bot token",
  "notify.tokenHint": "It is sent straight to the helper program and not kept in this window.",
  "notify.connect": "Connect",
  "notify.connecting": "Connecting…",
  "notify.startStep": "Now open your new bot in Telegram and send it /start. Then press the button.",
  "notify.findChat": "I sent /start",
  "notify.connected": "Connected to @{bot}. A test message was sent to your chat.",
  "notify.connectedNoName": "Connected. A test message was sent to your chat.",
  "notify.change": "Use a different bot",
  "notify.needOne": "Turn on at least one way to be notified.",
  "notify.error.bad_token": "Telegram does not accept that token. Check that you copied all of it.",
  "notify.error.no_message": "Your bot has not received a message yet. Send it /start in Telegram, then try again.",
  "notify.error.network": "Could not reach Telegram. Check your internet connection and try again.",
  "notify.error.send_failed": "Connected, but the test message could not be sent. Try again.",
  "notify.error.default": "Telegram said no: {message}",
  "notify.needToken": "Paste the token first.",

  "upwork.title": "Check the Upwork connection",
  "upwork.lead": "gigradar reads Upwork the way a browser does. We'll open a window once to make sure this works.",
  "upwork.note": "The window may show a security check from Upwork. If it asks you to click a box, click it. The window closes by itself.",
  "upwork.open": "Open the check",
  "upwork.running": "Checking… a window is open.",
  "upwork.retrying": "That didn't work yet. Trying again…",
  "upwork.ok": "It works. Found {count} jobs to start from.",
  "upwork.again": "Try again ({n} of {max})",
  "upwork.failedTitle": "That didn't work.",
  "upwork.error.window_failed": "The browser window was slow to start.",
  "upwork.error.webview2_missing": "Windows is missing a component (Microsoft Edge WebView2) that gigradar needs.",
  "upwork.error.blocked": "Upwork did not let the check through.",
  "upwork.error.default": "The check stopped: {message}",
  "upwork.error.crash": "The helper program stopped unexpectedly.",
  "upwork.installWebview2": "Get the missing component",
  "upwork.helpTitle": "Still stuck?",
  "upwork.help1": "Close other heavy programs and try once more; a busy PC can be slow to open the window.",
  "upwork.help2": "If a security check appears, click its box and wait a few seconds.",
  "upwork.help3": "If it keeps failing, you can continue and fix it later from the status page.",
  "upwork.skip": "Continue anyway",

  "model.title": "Download the scoring model",
  "model.lead": "To rate jobs, gigradar uses a small language model that runs on your PC. It is downloaded once (about 70 MB).",
  "model.start": "Download",
  "model.progress": "Downloading… {percent}%",
  "model.progressUnknown": "Downloading… {mb} MB so far",
  "model.verify": "Checking the download…",
  "model.ok": "The model is ready.",
  "model.failed": "The download did not finish: {message}",
  "model.retry": "Try again",
  "model.error.crash": "The helper program stopped unexpectedly.",

  "finish.title": "Almost done",
  "finish.lead": "gigradar will now schedule itself to check Upwork every 30 minutes and do a first run so you can see it working.",
  "finish.start": "Finish setup",
  "finish.stepSchedule": "Schedule the checks",
  "finish.stepRun": "Run the first check",
  "finish.stepJobs": "Look at the results",
  "finish.pending": "waiting",
  "finish.running": "working…",
  "finish.done": "done",
  "finish.failed": "failed",
  "finish.doneTitle": "You're all set",
  "finish.doneBody": "You can close this window. Checks run in the background every 30 minutes, even when the app is closed.",
  "finish.close": "Close",
  "finish.firstRun": "First check done: {seen} current jobs are noted. From now on you hear about new ones.",
  "finish.latest": "Latest jobs",
  "finish.noJobs": "No jobs yet. They appear after the next check.",
  "finish.score": "score {score}",
  "finish.noScore": "no score",
  "finish.openStatus": "Open the status page",
  "finish.errorSchedule": "Could not schedule the checks: {message}",
  "finish.errorRun": "The first check did not finish: {message}",
  "finish.retry": "Try again",
  "finish.applyFailed": "Could not save your settings: {message}",

  "home.title": "Home",
  "status.title": "Status",
  "status.lead": "This is how everything is doing.",
  "status.recheck": "Check again",
  "status.setupAgain": "Set up again",
  "status.checking": "Checking…",
  "status.overall.OK": "Everything works.",
  "status.overall.WARN": "Works, with a few things to look at.",
  "status.overall.FAIL": "Something needs fixing.",
  "status.level.OK": "OK",
  "status.level.WARN": "Check",
  "status.level.FAIL": "Problem",
  "status.summary.ok": "All set — next check at {time}",
  "status.summary.okNoTime": "All set — checks run every 30 minutes",
  "status.summary.one": "1 thing needs attention",
  "status.summary.many": "{n} things need attention",
  "status.home": "Your data is kept in {home}",

  "check.config": "Settings file",
  "check.profile": "Your profile",
  "check.telegram_token": "Telegram token",
  "check.telegram_api": "Telegram connection",
  "check.telegram_chat": "Telegram chat",
  "check.webview2_runtime": "Browser component (WebView2)",
  "check.webview_profile": "Upwork browser data",
  "check.model": "Scoring model",
  "check.store": "Job history",
  "check.scheduled_task": "Automatic checks",
  "check.recent_errors": "Recent problems",

  "fix.config": "Run the setup again.",
  "fix.profile": "Add a profile in the setup so jobs can be scored.",
  "fix.telegram_token": "Connect your Telegram bot again in the setup.",
  "fix.telegram_api": "Check your internet connection, or connect your bot again.",
  "fix.telegram_chat": "Connect your Telegram bot again in the setup.",
  "fix.webview2_runtime": "Install Microsoft Edge WebView2 (free), then check again.",
  "fix.webview_profile": "Run the Upwork check from the setup once.",
  "fix.model": "Download the scoring model from the setup.",
  "fix.store": "It is created by the first check. Run the setup to make one.",
  "fix.scheduled_task": "Finish the setup to schedule the automatic checks.",
  "fix.recent_errors": "Open the log file in your data folder for details.",
  "fix.openWebview2": "Download WebView2",
  "fix.btn.setup": "Set up again",
  "fix.btn.upwork": "Check Upwork",
  "fix.btn.model": "Download model",
  "fix.btn.task": "Schedule checks",
  "fix.btn.webview2": "Get WebView2",
  "fix.working": "Working…",

  "error.generic": "Something went wrong: {message}",
  "error.crash": "The helper program stopped unexpectedly (code {code}).",
  "error.noHelper": "The helper program was not found. Please reinstall gigradar.",
} as const;

export type Key = keyof typeof en;
type Table = Record<Key, string>;

const tables: Record<string, Table> = { en };
let currentLanguage = "en";

export function setLanguage(code: string): void {
  if (tables[code]) currentLanguage = code;
}

export function t(key: Key, vars: Record<string, string | number> = {}): string {
  const text = tables[currentLanguage][key] ?? en[key];
  return text.replace(/\{(\w+)\}/g, (match, name: string) => (name in vars ? String(vars[name]) : match));
}
